#pragma once

#include "hardware/pio.h"
#include <stdbool.h>
#include <stdint.h>

// Minimal WS2812 (NeoPixel) driver for RP2040 using PIO.
// - Uses the `ws2812.pio` program (header generated by CMake)
// - Writes pixels in GRB order (standard WS2812)

#define NEOPIXEL_WS2812_MAX_PIXELS 50

typedef struct neopixel_ws2812 {
  PIO pio;
  uint sm;
  uint pin;
  bool is_rgbw;
  uint num_pixels;
  uint32_t pixel_buf[NEOPIXEL_WS2812_MAX_PIXELS];
} neopixel_ws2812_t;

// Initialize a WS2812 strip on `pin` at `freq_hz` (normally 800000).
// `num_pixels` must be <= NEOPIXEL_WS2812_MAX_PIXELS.
void neopixel_ws2812_init(neopixel_ws2812_t *np, PIO pio, uint pin,
                          float freq_hz, bool is_rgbw, uint num_pixels);

// Set pixel 0 to an RGB value and flush the strip (backward compatible).
void neopixel_ws2812_put_rgb(neopixel_ws2812_t *np, uint8_t r, uint8_t g,
                             uint8_t b);

// Set one pixel by index (0..num_pixels-1) then flush.
void neopixel_ws2812_set_pixel_rgb(neopixel_ws2812_t *np, uint index,
                                  uint8_t r, uint8_t g, uint8_t b);

// Send current buffer to the strip.
void neopixel_ws2812_flush(neopixel_ws2812_t *np);

// Set pixel 0 to a raw GRB value (24-bit) and flush.
void neopixel_ws2812_put_grb_u32(neopixel_ws2812_t *np, uint32_t grb);
